### ISSUE TITLE
face_recognition出错

### ISSUE THREAD

**Issue by virgoC0der** [omega-Lee/PyQt5_Face_Recognition#4]
开始检测后，在人脸移入identification box框中，报错如下：
dist = np.sqrt(np.square(np.subtract(emb[i, :], compare_emb[j, :])))
ValueError: operands could not be broadcast together with shapes (512,) (128,)
请问是什么问题呢？

**Comment by akira4O4** [comment]
> 开始检测后，在人脸移入identification box框中，报错如下：
> dist = np.sqrt(np.square(np.subtract(emb[i, :], compare_emb[j, :])))
> ValueError: operands could not be broadcast together with shapes (512,) (128,)
> 请问是什么问题呢？

我没有出这种问题，可以自己百度一下。
